namespace _3._5_to_Roll20
{
    public enum SpellClass
    {
        Darkness,
        Glory,
        Madness,
        Creation,
        SorcererWizard,
        Repose,
        Cleric,
        Bard,
        Mind,
        Air,
        Druid,
        Animal,
        Paladin,
        Fire,
        Chaos,
        Blackguard,
        Ranger,
        Destruction,
        Good,
        Earth,
        Magic,
        Wizard,
        Protection,
        Luck,
        Law,
        Evil,
        Death,
    }
}
